name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Generate protos for example project
        run: pnpm i --frozen-lockfile && pnpm --filter tsgrpc-example protos

      - name: Run tests
        run: pnpm test:ci

      - name: Upload test converage
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/cli/coverage/test/lcov.info,./packages/server/coverage/test/lcov.info,./example/coverage/test/lcov.info
